# Generated by Django 4.1 on 2022-08-23 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreYapellido', models.CharField(max_length=30)),
                ('dni', models.IntegerField()),
                ('mail', models.EmailField(max_length=254)),
                ('telefono', models.IntegerField()),
                ('pais', models.CharField(max_length=20)),
                ('provincia', models.CharField(max_length=20)),
                ('ciudad', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('mail', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='DocDescargas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('idSocio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.socio')),
            ],
        ),
        migrations.CreateModel(
            name='CursosYcapacitaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('idSocio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.socio')),
            ],
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('nombreYapellido', models.CharField(max_length=30)),
                ('mail', models.EmailField(max_length=254)),
                ('dni', models.IntegerField()),
                ('ciudad', models.CharField(max_length=20)),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='ComentariosDeNoticias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('idSocio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.socio')),
            ],
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_socio', models.BooleanField()),
                ('mail', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.usuario')),
            ],
        ),
    ]
